# Generated by Django 3.1.3 on 2021-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%M/', verbose_name='Малюнок або фото:')),
                ('body', models.TextField(blank=True, null=True, verbose_name="Опис (не обов'язково):")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug (не заповнювати): ')),
            ],
        ),
    ]
