# Generated by Django 3.1.3 on 2021-03-15 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210315_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, message='Не меньше 2 символов')]),
        ),
    ]
